CREATE SEQUENCE SEQ_FOLLOW;

CREATE TABLE TBL_FOLLOW(
	FOLLOW_ID NUMBER CONSTRAINT PK_LIKE PRIMARY KEY,
	FOLLOWER_ID NUMBER NOT NULL,
	FOLLOWING_ID NUMBER NOT NULL,
	CONSTRAINT FK_FOLLOWER FOREIGN KEY(FOLLOWER_ID) REFERENCES TBL_USER(USER_ID),
	CONSTRAINT FK_FOLLOWING FOREIGN KEY(FOLLOWING_ID) REFERENCES TBL_USER(USER_ID)
);

DROP TABLE TBL_FOLLOW;

SELECT * FROM TBL_FOLLOW;

INSERT INTO TBL_FOLLOW 


INSERT INTO TBL_FOLLOW
(FOLLOW_ID, FOLLOWER_ID, FOLLOWING_ID)
VALUES(SEQ_FOLLOW.NEXTVAL, '23', '21');

SELECT F1.FOLLOWING_ID "내 계정", F1.FOLLOWER_ID  "내가 팔로우 한 사람", F2.FOLLOWING_ID "나를 팔로우 한 사람"
FROM TBL_FOLLOW F1 JOIN (SELECT FOLLOWING_ID, FOLLOWER_ID FROM TBL_FOLLOW WHERE FOLLOWER_ID = 'lss1234') F2
ON F1.FOLLOWING_ID = F2.FOLLOWER_ID;



/* 21번 회원이 팔로우한 사람의 수를 조회하는 쿼리 */
SELECT FOLLOWER_ID, COUNT(FOLLOWER_ID) "팔로우 한 사람 수" FROM TBL_FOLLOW WHERE FOLLOWING_ID = '21' GROUP BY FOLLOWER_ID;
/* 21번 회원을 팔로우한 사람의 수를 조회하는 쿼리 */
(SELECT FOLLOWER_ID "유저", COUNT(FOLLOWER_ID) "팔로우 한 사람 수" FROM TBL_FOLLOW WHERE FOLLOWER_ID = '21' GROUP BY FOLLOWER_ID);

/* 21번 회원의 팔로워 수와 팔로잉 수를 조회*/
SELECT F1.*
FROM TBL_FOLLOW F1 JOIN (SELECT FOLLOWER_ID, COUNT(FOLLOWER_ID) "팔로우 한 사람 수" FROM TBL_FOLLOW WHERE FOLLOWER_ID = '21' GROUP BY FOLLOWER_ID) F2
ON F1.FOLLOWING_ID = F2.FOLLOWER_ID;

/* lss1234라는 유저를 팔로잉한 사람들을 조회하기 위해 사용한 쿼리, 예상은 서브쿼리문으로 들어가려 했음*/
SELECT FOLLOWING_ID, FOLLOWER_ID FROM TBL_FOLLOW WHERE FOLLOWER_ID = 'lss1234';

DELETE FROM TBL_FOLLOW WHERE FOLLOW_ID = 9;














